version: '3'

services:
  backend:
    image: line-bot
    container_name: node-backend
    ports:
      - 4001:4001
    environment:
      # 系統設定
      - SERVER_NAME=template-nest
      - VERSION=default
      - SERVER_PORT=4001
      - JWT_SECRET=template-nest

      # Linebot
      - LINEBOT_ACCESS_TOKEN=JE9S+rCAIauE3uyh7XZtIaab2MOI0ma+zTgX44bNUvwITfXzpRrkX+y5F3XlsOSWqqTM0IZIEkAA6aUdvxXG5nHkO5BcAtqS2XPrWqRgiZ2ZEFBU4/y8KscKlHiKJdVUT7G03Z+tnqlJkAPgqAYq8VGUYhWQfeY8sLGRXgo3xvw=
      - LINEBOT_SIGNATURE_MENU=richmenu-d011dd9de40a2f8f3c1cd1d5f98a9d8c
      - LINEBOT_SHOWFILE_MENU=richmenu-01346e1b842295319392fb1c712b2762

      # postchain-sdk
      - POSTCHAIN_PRIVATE_KEY=76f7fd166f27f1ab24bad8216706979886c4b4dd21c84ab40cc8c7c6f2e5dbc7
      - POSTCHAIN_PUBLIC_KEY=03a96ec1d7f35f11731a76c470fe360a8f5a308d54387955fd02e6330363eda4fe

      # --------------------- 以下錯誤處理 ---------------------
      # 共用錯誤
      - ERR_DATA_MUST_BE_ARRAY=10001 傳入的資料必須為 array
      - ERR_DATA_MUST_BE_OBJECT=10002 傳入的資料必須為 object
      - ERR_FIELD_REQUIRED=10003 缺少資料欄位
      - ERR_BAD_REQUEST=10004 錯誤的請求格式
      - ERR_DATA_EXIST=10005 資料已存在

      # Auth 登入相關
      - ERR_AUTH_VALIDATE_BAD_ACCESS_TOKEN= 11001 無效的Access_Token
      - ERR_AUTH_REGISTER_USER_EXIST= 11002 已註冊使用者
      - ERR_AUTH_LOGIN_NOT_REGISTER_USER= 11003 尚未註冊使用者
      - ERR_AUTH_LOGIN_PASSWORD_NOT= 11004 密碼錯誤

      # User 相關錯誤
      - ERR_USER_NOT_FOUND= 12001 找不到使用者
      - ERR_USER_EXIST= 12002 使用者已存在

      # 系統核心錯誤 相關錯誤
      - ERR_SYSTEM_ERROR=99001 系統錯誤
      - ERR_RESOURCE_NOT_FOUND=99002 找不到這筆資料
      - ERR_INVALID_OBJECT_ID=99003 不合格的ObjectId請求已被記錄
      - ERR_ERROR_UNDEFINED=99998 未定義錯誤
      - ERR_BAD_ERROR_CODE=99999 不正確的錯誤呼叫，請聯絡偷懶的後端人員
